project6/config/routes.rb
Rails.application.routes.draw do
  resources :evaluates
  resources :ratings
  resources :courses
  resources :groups
  resources :memberships
  resources :welcomes
  get '/welcomes/confirmation', to: 'welcomes#confirmation'
 
  devise_for :users
  root 'welcomes#index'

  get  '/signup', to: 'welcomes#signup'
  get  '/login', to: 'welcomes#login'



end
# controllers {sesions: "users/sessions"}

project6/app/models/user.rb
class User < ApplicationRecord
  has_many :memberships
  has_many :ratings
  has_many :groups, :through => :memberships
  has_many :courses
  has_many :evaluates

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

project6/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :destroy]

  # GET /courses
  # GET /courses.json
  def index
     # URL redirection to home page if user is not signed in
    if !user_signed_in?
      redirect_to welcomes_path
    end
    # URL redirection to homepage if user signed in is not admin
    if user_signed_in? and !current_user.try(:admin?)
      redirect_to welcomes_path
    end
    # show all courses
    @courses = Course.where(user_id: current_user)
  end


  # GET /courses/1
  # GET /courses/1.json
  def show
    # URL redirection to home page if user is not signed in
    if !user_signed_in?
      redirect_to welcomes_path
    end

    # URL redirection to homepage if user signed in is not admin
    if user_signed_in? and !current_user.try(:admin?)
      redirect_to welcomes_path
    end
    # show all groups for a course
    @groups = Group.where(course_id: @course.id).all||nil

  end

  # GET /courses/new
  def new
   # URL redirection to home page if user is not signed in
    if !user_signed_in?
      redirect_to welcomes_path
    end

    # URL redirection to homepage if user signed in is not admin
    if user_signed_in? and !current_user.try(:admin?)
      redirect_to welcomes_path
    end
    # new course add page
    @course = current_user.courses.build
  end

  # GET /courses/1/edit
  def edit
    # URL redirection to home page if user is not signed in
    if !user_signed_in?
      redirect_to welcomes_path
    end

    # URL redirection to homepage if user signed in is not admin
    if user_signed_in? and !current_user.try(:admin?)
      redirect_to welcomes_path
    end
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = current_user.courses.build(course_params)
    @course.semester = params[:semester]

    # Creates a new course and saves it
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    # remove all groups belonging to a course
    for i in 0...@course.group_ids.length
      Group.find(@course.group_ids[i]).destroy
    end
    # remove the course
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:cname, :semester, :user_id)
    end

end

project6/app/helpers/courses_helper.rb
module CoursesHelper
end

project6/app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% semester =[['SP19','SP19'],['SU19','SU19'],['AU19','AU19'],['SP20','SP20'],['SU20','SU20'],['AU20','AU20']] %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :cname %>
    <%= form.hidden_field :user_id, :value => current_user.id  %>
  </div>

  <div class="field">

    <%= form.label :semester %>
    <%= select_tag(:semester, options_for_select(semester), :prompt => "Select") %>
  </div>

  <div class="actions">
    <%= form.submit "Create Class", :class => "btn btn-default" %>
  </div>
<% end %>

project6/app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

project6/app/views/courses/index.html.erb
<h1>Classes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Semester</th>
      <th>Number of Groups</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if current_user.try(:admin?) %>
      <% @courses.each do |course| %>
	    
	<tr><% if user_signed_in? and course.user_id == current_user.id%>
		<td><%= link_to course.cname, course %></td>
	        <td><%= course.semester %></td>
              	<td><%= course.group_ids.length %></td>
              <td>
<%= link_to 'Add Group', new_group_path(:course_id => course.id), :class => "action" %>
<%= link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?' }, :class => "action"%>
              </td>
            <% end %>
          <% end %>
        </tr>
	<% end %>
  </tbody>
</table>
<br>
<% if current_user.try(:admin?) %>
  <%= link_to 'New Class', new_course_path, :class => "new" %></br>
  <%= link_to 'Go to Groups', groups_path %>
<% end %>

project6/app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

project6/app/views/courses/show.html.erb
<h1><%= @course.cname %> - <%= @course.semester %></h1>
 
<h2>Groups:</h2>
<% if @course.group_ids.length == 0 %>
	<h2>There are currently no groups in this class</h2>
<% end %>

<table><tbody>
<% for i in 0...@course.group_ids.length %>
	
	<tr><td><h3><%= link_to Group.find(@course.group_ids[i]).gname, memberships_path(:group_id => @course.group_ids[i])  %>	</h3></td></tr>
<% end %>
</tbody></table>
<br><%= link_to 'New Group', new_group_path(:course_id => @course.id), :class => "new" %>
<br><%= link_to 'Go to Groups', groups_path %>
<br><%= link_to 'Go to Classes', courses_path, :class => "btn btn-default" %>