project6/config/routes.rb
Rails.application.routes.draw do
  resources :evaluates
  resources :ratings
  resources :courses
  resources :groups
  resources :memberships
  resources :welcomes
  get '/welcomes/confirmation', to: 'welcomes#confirmation'
 
  devise_for :users
  root 'welcomes#index'

  get  '/signup', to: 'welcomes#signup'
  get  '/login', to: 'welcomes#login'



end
# controllers {sesions: "users/sessions"}

project6/app/models/user.rb
class User < ApplicationRecord
  has_many :memberships
  has_many :ratings
  has_many :groups, :through => :memberships
  has_many :courses
  has_many :evaluates

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

project6/app/models/welcome.rb
class Welcome < ApplicationRecord
end

project6/app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]

  def confirmation
  end

  # GET /welcomes
  # GET /welcomes.json
  def index
    @welcomes = Welcome.all
  end

  # GET /welcomes/1
  # GET /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes
  # POST /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1
  # PATCH/PUT /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: 'Welcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_params
      params.fetch(:welcome, {})
    end
end

project6/app/helpers/welcomes_helper.rb
module WelcomesHelper
end

project6/app/views/welcomes/_form.html.erb
<%= form_with(model: welcome, local: true) do |form| %>
  <% if welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
      <% welcome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h1>Evaluations created!</h1>

  <% @users = User.all.collect %>
  <% @members = [] %>
  <% for i in 0...Group.find(params[:group_id]).membership_ids.length %>
    <% @users.each do |user| %>
      <% if user.membership_ids.include? Group.find(params[:group_id]).membership_ids[i] %>
      <% @members.push user %>
    <% end %>
    <% end %>
  <% end %>

  <% @members.each_with_index do |member, n|  %>
    <% @members.each_with_index do |member, m| %>
      <% @eval = Evaluate.new(:group_id => Group.find(params[:group_id]).id, :user_id => @members[n].id, :ratee_id => @members[m].id, :attempt => false) %>
      <% @eval.save %>
    <% end %>
  <% end %>

  <br><%= link_to 'Back to Groups', groups_path, :class => "btn btn-default" %>
  <br><%= link_to 'Back to Classes', courses_path, :class => "btn btn-default" %>
<% end %>

project6/app/views/welcomes/confirmation.html.erb
<h1>Evaluations sent!</h1>

<% @users = User.all.collect %>
<% @members = [] %>

<!-- Sends out evaluations to all members of a selected group --> 
<% for i in 0...Group.find(params[:group_id]).membership_ids.length %>
	<% @users.each do |user| %>
		<% if user.membership_ids.include? Group.find(params[:group_id]).membership_ids[i] %>
			<% @members.push user %>
		<% end %>
	<% end %>
<% end %>

<% for i in 0...@members.length %>
	<% for j in 0...@members.length %>
		<% if i != j %>
			<% @eval = Evaluation.new(:group_id => Group.find(params[:group_id]).id, :rater_id => @members[i].id, :ratee_id => @members[j].id, :attempt => false) %>
			<% @eval.save %>
		<% end %>
	<% end %>
<% end %>

<%= link_to 'Back', groups_path, :class => "btn btn-default" %>

project6/app/views/welcomes/edit.html.erb
<h1>Editing Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

project6/app/views/welcomes/index.html.erb
<table class="landing-page">
  <tr>
    <td class="text">
      <h1>Give credit where credit's due</h1>
      <h3>RateMyPeers is an online academic tool that helps students provide feedback for their teammates during group projects. Instructors set up the groups and can see the ratings to help them quickly notice and address any issues in the class.<h3>
    </td>
    <td class="media"> <%=  image_tag("info-12.png") %> </td>
  </tr>
</table>
<table class="landing-page">
  <tr>
    <td class="media">
      <%= video_tag("demo.webm",autoplay:true,loop:true,controls:true) %>
    </td>
    <td class="text">
      <h1>How it works</h1>
      <h3>Our intuitive design makes it easy to get the grade you deserve in no time at all. Take a look at the video to the left or the list below to get an idea of the workflow.</h3>
      <ul>
        <li>Instructor creates the class</li>
        <li>Instructor creates groups and adds students to the groups</li>
        <li>After each project, the students rate their teammates</li>
        <li>Each student's overall score updates automatically based on team ratings</li>
      </ul>
    </td>
  </tr>
</table>
<table class="landing-page">
  <tr>
    <td class="split">
      <h1>Great for Students</h1>
      <h3>Make sure that good teammates get rewarded, and bad ones don't get a grade they didnt earn. You'll have an overall rating that sticks with you forever, and you can see other students' ratings when choosing a group.</h3>
    </td>
    <td class="split">
          <h1>Great for Instructors</h1>
          <h3>Keep your class running smoothly and be confident that your students are getting the credit they earned. We help you discover problems as soon as they surface, so you can resolve them and focus on teaching.</h3>
        </td>
  </tr>
</table>

<%= link_to "Get Started Now!",new_user_registration_path,:class=>"get-started-button" %>
<br><br><br><br><br>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script>
$(document).ready(function(){
	$(".content>*").unwrap()
});
</script>

project6/app/views/welcomes/new.html.erb
<%= render 'form', welcome: @welcome %>

project6/app/views/welcomes/old-index.html.erb
<% if !user_signed_in? %>
      <h1>Peer Evaluations</h1>
      <h1>There is an admin user created. Use test.1@osu.edu with password as the password</h1>
      <ul>
	<li><%= link_to "Register Now", new_user_registration_path, :class => "btn btn-default text-center" %><li>
        <li>This is the index page which will provide you with instructions and how to use our website</li>
        <li>For team members: In order to get more information, please go to app/views/welcomes/index.html.erb</li>
        <li>Use the navigation bar above to get to the sign up and log in pages</li>
        <li>Easy access to the index of peer evaluaton: <a href="/evaluations">Peer evaluation</a></li>
      </ul>

<% end %>


<% if user_signed_in? and current_user.try(:admin?) %>
	<h1>Welcome to the Peer Evaluation website by infinite_loop</h1>
	<h2>You are signed in as an instructor</h2>
	<h2>To get started, click here: <a href="/courses">Classes</a></h2>
	<h2>Other important links:</h2>
	<h3><a href="/welcomes">Home Page</a></h2>
	<h3><a href="/courses">Course Page</a></h2>
	<h3><a href="/groups">Groups Page</a></h2>
	<h3><a href="/ratings">Ratings Page</a></h2>
<% end %>


<% if user_signed_in? and !current_user.try(:admin?) %>
	<h1>Welcome to the Peer Evaluation website by infinite_loop</h1>
	<h2>You are signed in as a student. To be an admin, go to terminal. Type in $ rails c. Change the admin boolean attribute to true</h2>
	<h2>To get started, click here: <a href="/groups">Groups</a></h2>
	<h2>Other important links:</h2>
	<h3><a href="/welcomes">Home Page</a></h2>
	<h3><a href="/courses">Course Page</a></h2>
	<h3><a href="/groups">Groups Page</a></h2>
	<h3><a href="/ratings">Ratings Page</a></h2>
<% end %>

project6/app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>

project6/app/views/welcomes/signup.html.erb
<div class="signup">
    <h1>Getting Started</h1>
    <h3>Are you a <%= link_to "Student", "user_new_user_registration_path"  %> or an <%= link_to "Instructor",instructor_signup_path %>?<br><br>(Select one) </h3>
</div>