project6/config/routes.rb
Rails.application.routes.draw do
  resources :evaluates
  resources :ratings
  resources :courses
  resources :groups
  resources :memberships
  resources :welcomes
  get '/welcomes/confirmation', to: 'welcomes#confirmation'
 
  devise_for :users
  root 'welcomes#index'

  get  '/signup', to: 'welcomes#signup'
  get  '/login', to: 'welcomes#login'



end
# controllers {sesions: "users/sessions"}

project6/app/models/group.rb
class Group < ApplicationRecord
	has_many :memberships
	has_many :evaluates
	has_many :users, :through => :memberships
	belongs_to :course
end

project6/app/controllers/groups_controller.rb
 class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    # URL redirection to home page if user is not signed in
    if !user_signed_in?
      redirect_to welcomes_path
    end
    if user_signed_in? and current_user.try(:admin?)
      @groups = Group.where(user_id: current_user)
    else
      @groups = Group.all
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  # URL redirection to home page if user is not signed in
    if !user_signed_in?
      redirect_to welcomes_path
    end

  end

  # GET /groups/new
  def new
    # URL redirection to home page if user is not signed in
    if !user_signed_in?
      redirect_to welcomes_path
    end
    # Create a new group
    @group = current_user.groups.build
  end

  # GET /groups/1/edit
  def edit
     # URL redirection to home page if user is not signed in
    if !user_signed_in?
      redirect_to welcomes_path
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = current_user.groups.build(group_params)
    # Create and save a group
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    # Update a group
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    Evaluate.all.collect.each do |evaluate|
      if evaluate.group_id == @group.id
        evaluate.destroy
      end
    end

    # Remove all Ratings for a selected group
    Rating.all.collect.each do |rating|
      if rating.group_id == @group.id
        rating.destroy
      end
    end

    # Remove members of a group
    for i in @group.membership_ids
      Membership.find(i).destroy
    end

    # Remove the group
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:gname, :course_id, :user_id)
    end
end

project6/app/helpers/groups_helper.rb
module GroupsHelper
end

project6/app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :gname %>
    <%= form.hidden_field :user_id, :value => current_user.id  %>
    <%= form.hidden_field :course_id, :value => Course.find(params[:course_id]).id  %>
  </div>

  <div class="actions">
    <%= form.submit "Create Group", :class => "btn btn-default" %><br>
    <%= link_to 'Back to Groups', groups_path, :class => "btn btn-default" %><br>
    <%= link_to 'Back to Classes', courses_path, :class => "btn btn-default" %>
  </div>

<% end %>

project6/app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

project6/app/views/groups/index.html.erb
<% if !current_user.try(:admin?) %>
<h1>Groups</h1>
<% else %>
<h1>Manage Groups</h1>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Members</th>
      <th>Class</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <% if user_signed_in? and !current_user.try(:admin?) %>
      	<% for i in 0...group.membership_ids.length %>
           <% if current_user.membership_ids.include? group.membership_ids[i] %>
      	      <tr>
                 <td><%= link_to group.gname, group %></td>
	               <td><%= group.membership_ids.length %></td>
                 <td><%= Course.find(group.course_id).cname %></td>
                 <td><%= link_to 'Show',group, :class=>"action" %>
                 </td>
              </tr>
           <% end %>
        <% end %>
      <% end %>
    <% end %>

    <!-- If user signed in is admin and owner of group, show each group name, members, and link to detail of each group -->
    <% if current_user.try(:admin?) %>
      <% @groups.each do |group| %>
        <tr>
          <td><%= link_to group.gname, group %></td>
          <td><%= group.membership_ids.length %></td>
          <td><%= Course.find(group.course_id).cname %></td>
          <td>
                  
              <% evalsFinished = true %>
                  <% for i in 0...group.evaluate_ids.length %>
                      <% if Evaluate.find(group.evaluate_ids[i]).attempt == false %>
                        <% evalsFinished = false %>
                      <% end %>
                  <% end %>

                  <% if group.evaluate_ids.empty? || evalsFinished %>
                  <% if group.membership_ids.length > 1 %>
                    <%= link_to 'Send Evaluations to Students', new_welcome_path(:group_id => group.id), data: { confirm: 'Are you sure you want to open evaluations for ' + group.gname + '?'}, :class=>"action"%>
                  <% end %>
                  <% end %>

                  <% resultsExist = false %>
                  <% for i in 0...group.evaluate_ids.length %>
                    <% if Evaluate.find(group.evaluate_ids[i]).attempt == true %>
                      <% resultsExist = true %>
                    <% end %>
                  <% end %>

                  <% if resultsExist %>
                    <%= link_to 'View Evaluation Results', ratings_path(:group_id => group.id) , :class=>"action" %>
                  <% end %>

              <%= link_to 'Add Member', new_membership_path(:group_id => group.id), :class=>"action" %>
              <%= link_to 'Delete', group, method: :delete, data: { confirm: 'Are you sure you want to delete ' + group.gname + '?'}, :class=>"action" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<!-- <br><%= link_to 'Back to Groups', groups_path, :class => "btn btn-default" %>
 --><br><%= link_to 'Back to Classes', courses_path, :class => "btn btn-default" %>

project6/app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

project6/app/views/groups/show.html.erb
<h1><%= @group.gname.capitalize %></h1>
<% if @group.membership_ids.length == 0 %>	
    <%= "There are currently no members in this group" %>	
<% else %>	
<table><thead><tr><td>User</td><td>Email</td><td>Score</td></tr></thead><tbody>
<% for i in 0...@group.membership_ids.length %>
	<tr><td>
	<%= User.find(Membership.find(@group.membership_ids[i]).user_id).Fname %> <%= User.find(Membership.find(@group.membership_ids[i]).user_id).Lname %>
	</td>
	<td>
	<%= User.find(Membership.find(@group.membership_ids[i]).user_id).email %>
	</td>
	<td>
	<%= User.find(Membership.find(@group.membership_ids[i]).user_id).score %>
	</td></tr>

<% end %>
</tbody></table>
<% end %>
    <br><%= link_to 'Back to Groups', groups_path, :class => "btn btn-default" %>